---
- name: Set script_args to json
  set_fact:
    script_args: "{{ script_args | to_json }}"

- name: Display script_args
  debug:
    msg: "script_args is {{ script_args }}"

- name: Run the Python script to validate JSON in the cloned repository
  ansible.builtin.command:  
    cmd: >
      python3 "{{ testbed_tmp_path }}/{{ script_name }}"
    stdin: "{{ script_args }}"
  register: result_output

- name: Set environment variable with validation result
  ansible.builtin.set_fact:
    script_result: "{{ result_output.stdout }}"

- name: Display the validation result
  ansible.builtin.debug:
    msg: "script_result is {{ script_result }}"
