---
- name: Stop and disable nodeengine service
  systemd:
    name: nodeengine
    state: stopped
    enabled: false
  become: true

- name: Stop and disable netmanager service
  systemd:
    name: netmanager
    state: stopped
    enabled: false
  become: true

- name: Remove nodeengine service file
  file:
    path: /etc/systemd/system/nodeengine.service
    state: absent
  become: true

- name: Remove netmanager service file
  file:
    path: /etc/systemd/system/netmanager.service
    state: absent
  become: true

- name: Remove NodeEngine binary
  file:
    path: /bin/NodeEngine
    state: absent
  become: true

- name: Remove nodeengined binary
  file:
    path: /bin/nodeengined
    state: absent
  become: true

- name: Remove log directory for Oakestra
  file:
    path: /var/log/oakestra
    state: absent
  become: true

- name: Reload systemd to reflect changes
  systemd:
    daemon_reload: true
  become: true
