- name: Check net repo exists
  ansible.builtin.include_role: 
    name: ensure-oakestra-repo-is-cloned
  vars:
    repo: "{{ oak_net_repo_link }}"
    path: "{{ oak_net_repo_path }}"
    branch: "{{ oak_net_repo_branch }}" 
    commit: "{{ oak_net_repo_commit}}"

# This is installing go in a wierd path. Check if config is correct.
- name: Check if Go is installed
  ansible.builtin.include_role:
    name: gantsign.golang
  vars:
    golang_version: '1.21.3'
    golang_install_dir: '/opt/go/1.21.3'

- name: Build NodeEngine
  shell: |
    export PATH={{ golang_install_dir }}/bin:$PATH
    cd {{ oak_net_repo_path }}/node-net-manager/build && ./build.sh
  args:
    executable: /bin/bash
  become: true

- name: Copy NetManager binary to build directory
  shell: >
    cp {{ oak_net_repo_path }}/node-net-manager/build/bin/$(dpkg --print-architecture)-NetManager
    {{ oak_net_repo_path }}/node-net-manager/build/
  become: true


- name: Install NodeEngine
  shell: "cd {{ oak_net_repo_path }}/node-net-manager/build/ && ./install.sh $(dpkg --print-architecture)"
  args:
    executable: /bin/bash
  become: true

- name: Create config file directory /etc/netmanager
  ansible.builtin.file:
    path: "/etc/netmanager"
    state: directory
  ignore_errors: true
  become: true

- name: Copy netcfg.json config files of net manager
  ansible.builtin.copy:
    src: "{{ oak_net_repo_path }}/node-net-manager/config/netcfg.json"
    dest: "/etc/netmanager/netcfg.json"
    remote_src: true
  become: true

- name: Copy tuncfg.json config files of net manager
  ansible.builtin.copy:
    src: "{{ oak_net_repo_path }}/node-net-manager/config/tuncfg.json"
    dest: "/etc/netmanager/netcfg.json"
    remote_src: true
  become: true

- name: Config netmanager public address
  environment:
    PUB_ADDR: "{{ nodeIP }}"
    CFG_DIR: "{{ oak_net_repo_path }}"
  shell: sed "s/0.0.0.0/$PUB_ADDR/" $CFG_DIR/node-net-manager/config/netcfg.json > /etc/netmanager/netcfg.json
  become: true

- name: Config netmanager Cluster URL
  environment:
    CLUSTER_ADDR: "{{ clusterIP }}"
    CFG_DIR: "{{ oak_net_repo_path }}"
  shell: 'sed "s/ClusterUrl.*/ClusterUrl\": \"$CLUSTER_ADDR\",/g" /etc/netmanager/netcfg.json > /etc/netmanager/netcfg.tmp.json && cp /etc/netmanager/netcfg.tmp.json /etc/netmanager/netcfg.json'
  become: true