- name: Check if directory exists
  ansible.builtin.include_role:
    name: ensure-oakestra-repo-is-cloned
  vars:
    repo: "{{ oak_repo_link }}"
    path: "{{ oak_repo_path }}"
    branch: "{{ oak_repo_branch }}"
    commit: "{{ oak_repo_commit }}"


- name: Check if Go is installed
  ansible.builtin.include_role: 
    name: gantsign.golang
  vars:
    golang_version: '1.21.3'
    golang_install_dir: '/opt/go/1.21.3'

- name: Build NodeEngine
  shell: |
    export PATH={{ golang_install_dir }}/bin:$PATH
    cd {{ oak_repo_path }}/go_node_engine/build && ./build.sh
  args:
    executable: /bin/bash
  become: true


- name: Install NodeEngine
  shell: "cd {{ oak_repo_path }}/go_node_engine/build && ./install.sh $(dpkg --print-architecture)"
  args:
    executable: /bin/bash
  become: true