---
- hosts: "{{ group_1doc }}"
  roles:
    - root-cluster-running-check
    - worker-running-check
  vars:
    docker_compose_file: "{{ oak_repo_path }}/run-a-cluster/1-DOC.yaml"

- hosts: "{{ group_clusters_full }}"
  roles:
    - root-cluster-running-check
  vars:
    docker_compose_file: "{{ oak_repo_path }}/cluster_orchestrator/docker-compose.yml"


- hosts: "{{ group_root_full }}"
  roles:
    - root-cluster-running-check
  vars:
    docker_compose_file: "{{ oak_repo_path }}/root_orchestrator/docker-compose.yml"


- hosts: "{{ group_workers_full }}"
  roles:
    - worker-running-check
