---
- name: (1DOC Topology) - Retrieve hostnames of workers
  hosts: "{{ group_1doc }}"
  gather_facts: true
  tasks:
    - name: Retrieve hostname for {{ inventory_hostname }}
      shell: |
        hostname
      register: local_hostname

    - name: Add {{ inventory_hostname }} to hostname list
      set_fact:
        hostname_list: "{{ local_hostname.stdout }}"
      delegate_facts: true

- name: (1DOC Topology) - App Deploy
  hosts: localhost
  roles:
    - role: topology-app-deploy
      vars:
        local_hostname: "{{ local_hostname }}"
        group_root: "{{ group_1doc }}"
        group_clusters: "{{ group_1doc }}"
        topology_desc: "{{ topology_desc }}"
      when: onedoc and not mdoc

- name: (MDNC Topology) - Retrieve hostnames of workers
  hosts: "{{ group_mdnc_workers }}"
  gather_facts: true
  tasks:
    - name: Retrieve hostname for {{ inventory_hostname }}
      shell: |
        hostname
      register: local_hostname

    - name: Add {{ inventory_hostname }} to hostname list
      set_fact:
        hostname_list: "{{ local_hostname.stdout }}"
      delegate_facts: true

- name: (MDNC Topology) - App Deploy
  hosts: localhost
  roles:
    - role: topology-app-deploy
      vars:
        local_hostname: "{{ local_hostname }}"
        group_root: "{{ group_mdnc_root }}"
        group_clusters: "{{ group_mdnc_clusters }}"
        topology_desc: "{{ topology_desc }}"
      when: not onedoc and not mdoc


- name: (M-DOC) - Retrieve hostnames of workers
  hosts: "{{ group_mdoc_workers }}"
  gather_facts: true
  tasks:
    - name: Retrieve hostname for {{ inventory_hostname }}
      shell: |
        hostname
      register: local_hostname

    - name: Add {{ inventory_hostname }} to hostname list
      set_fact:
        hostname_list: "{{ local_hostname.stdout }}"
      delegate_facts: true

- name: (M-DOC) - App Deploy
  hosts: localhost
  roles:
    - role: topology-app-deploy
      vars:
        local_hostname: "{{ local_hostname }}"
        group_root: "{{ group_mdoc_root }}"
        group_clusters: "{{ group_mdoc_root }}"
        topology_desc: "{{ topology_desc }}"
      when: not onedoc and mdoc
