---
    - name: Trigger GitHub Event via API
      vars:
        GITHUB_USERNAME: "oakestra"
        GITHUB_REPO: "awx-testbed-tests"
      uri:
        url: "https://api.github.com/repos/{{ GITHUB_USERNAME }}/{{ GITHUB_REPO }}/dispatches"
        method: POST
        headers:
          Accept: "application/vnd.github+json"
          Authorization: "Bearer {{ GITHUB_API_TOKEN }}"
          X-GitHub-Api-Version: "2022-11-28"
        body: 
          event_type: "api_call"
          client_payload: 
            output: "AWX Testbed Output"
            integration: true
            topology_descriptor: "{{ topology_desc | to_json }}"
            result: "{{ result }}"
        body_format: json
        status_code: [204]
      delegate_to: localhost