- name: Execute 1DOC template if one_doc_enabled is true
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fail if deploy_1doc is false
      fail:
        msg: "Deployment is skipped because deploy_1doc is false."
      when: not deploy_1doc

  

- name: Deploy components for 1DOC topology
  hosts: "{{ group_1doc }}"
  gather_facts: false
  tasks:
    - name: Retrieve current hostname IP address
      set_fact:
        current_ip: "{{ hostvars[inventory_hostname].ansible_host | default(hostvars[inventory_hostname].ansible_ssh_host, 'IP address not found') }}"  

    - name: Check current ip validity
      fail:
        msg: "IP address not found for current node {{ inventory_hostname }}"
      when: current_ip == "IP address not found"

    - name: Entrypoint to ensure cloned repo (node {{ inventory_hostname }})
      include_role:
        name: ensure-oakestra-repo-is-cloned
      vars:
        path: "{{ oak_repo_path }}"
        repo: "{{ oak_repo_link }}"
        branch: "{{ oak_repo_version }}"
        commit: "{{ commit }}"
        
      
    - name: Entrypoint to start 1DOC (node {{ inventory_hostname }})
      include_role:
        name: start-1-doc
      vars:
        rootIP: "{{ current_ip }}"
        clusterName: "{{ inventory_hostname }}"
        clusterLocation: ""
        additionalComposeOverrides: "-f override-alpha-versions.yaml"

 # roles:
 #   - ensure-oakestra-repo-is-cloned
 #   - start-1-doc
 # vars:
 #   params: "-f run-a-cluster/override-alpha-versions.yaml"
 #   path: "{{ oak_repo_path }}"
 #   repo: "{{ oak_repo_link }}"
 #   branch: "{{ oak_repo_version }}"
