---
################# 1DOC - Stop and Cleanup Components ##########################################
- hosts: "{{ group_1doc }}"
  roles:
    - unset-role-availability
    - kill-all-workers
  tasks:
    # Stop and free cluster and root nodes
    - name: (1DOC) Kill root and cluster containers on node {{ inventory_hostname }}
      include_role:
        name: kill-root-cluster
      vars:
        components_path: "/run-a-cluster/1-DOC.yaml"
        repo_path: "{{ oak_repo_path }}"

    # Clean files on node
    - name: (1DOC) Clean files node on node {{ inventory_hostname }}
      ansible.builtin.include_role:
        name: cleanup-root-cluster
      vars:
        repo_path: "{{ oak_repo_path }}"
        net_repo_path: "{{ oak_net_repo_path }}"


################# MDNC - Stop and Cleanup Components ##########################################
####### Stop and free worker nodes
- hosts: "{{ group_mdnc_workers }}"
  roles:
    - unset-role-availability
    - kill-all-workers

###### Stop and free cluster nodes
- hosts: "{{ group_mdnc_clusters }}"
  tasks:
    - name: (MDNC) Kill cluster processes on node {{ inventory_hostname }}
      include_role:
        name: kill-root-cluster
      vars:
        components_path: "/cluster_orchestrator/docker-compose.yml"
        repo_path: "{{ oak_repo_path }}"

    - name: (MDNC) Clean cluster node on node {{ inventory_hostname }}
      ansible.builtin.include_role:
        name: cleanup-root-cluster
      vars:
        repo_path: "{{ oak_repo_path }}"
        net_repo_path: "{{ oak_net_repo_path }}"

    - name: (MDNC) Change status of cluster node {{ inventory_hostname }} to free
      ansible.builtin.include_role:
        name: unset-role-availability

###### Stop and free root nodes
- hosts: "{{ group_mdnc_root }}"
  tasks:
    - name: (MDNC) Kill root processes on node {{ inventory_hostname }}
      include_role:
        name: kill-root-cluster
      vars:
        components_path: "/root_orchestrator/docker-compose.yml"
        repo_path: "{{ oak_repo_path }}"

    - name: (MDNC) Clean cluster node on node {{ inventory_hostname }}
      include_role:
        name: cleanup-root-cluster
      vars:
        components_path: "{{ root_components_path }}"
        repo_path: "{{ oak_repo_path }}"
        net_repo_path: "{{ oak_net_repo_path }}"

    - name: Change status of cluster node {{ inventory_hostname }} to free
      ansible.builtin.include_role:
        name: unset-role-availability
###############################################################################################

################# MDOC - Stop and Cleanup Components ##########################################
####### Stop and free worker nodes
- hosts: "{{ group_mdoc_workers }}"
  roles:
    - unset-role-availability
    - kill-all-workers

###### Stop and free cluster and root nodes
- hosts: "{{ group_mdoc_root }}"
  tasks:
    - name: (MDOC) Set cluster_components_path for cluster services
      set_fact:
        cluster_omponents_path: "/cluster_orchestrator/docker-compose.yml"

    - name: (MDOC) Debug oak_repo_path and components_path
      debug:
        msg: "oak_repo_path: {{ oak_repo_path }}, components_path: {{ cluster_omponents_path }}"

    - name: (MDOC) Kill cluster processes on node {{ inventory_hostname }}
      include_role:
        name: kill-root-cluster
      vars:
        components_path: "/cluster_orchestrator/docker-compose.yml"
        repo_path: "{{ oak_repo_path }}"

    - name: (MDOC) Kill root processes on node {{ inventory_hostname }}
      include_role:
        name: kill-root-cluster
      vars:
        components_path: "/root_orchestrator/docker-compose.yml"
        repo_path: "{{ oak_repo_path }}"

    - name: (MDOC) Clean repository files from {{ inventory_hostname }}
      ansible.builtin.include_role:
        name: cleanup-root-cluster
      vars:
        repo_path: "{{ oak_repo_path }}"
        net_repo_path: "{{ oak_net_repo_path }}"

    - name: (MDOC) Change status of node {{ inventory_hostname }} to free
      ansible.builtin.include_role:
        name: unset-role-availability
################# MDOC - Stop and Cleanup Components #################
