---
- name: Retrieve topology descriptor JSON from Git repository
  hosts: localhost
  vars:
    repo: "https://github.com/TheDarkPyotr/ansible-tests"

  gather_facts: no

  tasks:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: repo
      register: temp_repo_dir

    - name: Clone the repository
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{{ temp_repo_dir.path }}"
        version: "main" # Branch of testbed repository
        force: yes

    - name: Checkout the specific commit
      ansible.builtin.command:
        cmd: git checkout HEAD
        chdir: "{{ temp_repo_dir.path }}"
      register: git_checkout

    - name: Ensure the commit checkout was successful
      ansible.builtin.assert:
        that:
          - git_checkout.rc == 0
        fail_msg: "Failed to checkout commit {{ commit }}"

    - name: Inspect the cloned repository
      ansible.builtin.find:
        paths: "{{ temp_repo_dir.path }}"
        recurse: yes
      register: files

    - name: Display all files in the cloned repository
      ansible.builtin.debug:
        msg: "{{ files.files | map(attribute='path') | list }}"
        
    - name: Read {{ topology_descriptor }} topology descriptor JSON file
      ansible.builtin.slurp:
        src: "{{ temp_repo_dir.path }}/topologies/{{ topology_descriptor }}"
      register: json_file_content

    - name: Decode {{ topology_descriptor }} JSON content
      set_fact:
        topology_descriptor_content: "{{ json_file_content.content | b64decode }}"

    - name: Display {{ topology_descriptor }}
      ansible.builtin.debug:
        msg: "{{ topology_descriptor_content }}"

    - name: Support execution for topology validation {{ temp_repo_dir.path }}
      command: python3 "{{ temp_repo_dir.path }}"/utils/validator.py "{{ temp_repo_dir.path }}/{{ topology_descriptor }}"
      register: validation_result

    - name: Ensure the validation script was successful
      ansible.builtin.assert:
        that:
          - validation_result.rc == 0
        fail_msg: "Failed to validate the topology descriptor"

    - name: Retrieve validation result
      ansible.builtin.set_fact:
        TOPOLOGY_VALIDITY: "{{ validation_result.stdout }}"

    - name: Fail if topology_validity is false
      fail:
        msg: "Topology descriptor {{ topology_descriptor }} is not valid"
      when: not TOPOLOGY_VALIDITY
      
    - name: "Set facts for provisioning workflow"
      set_stats:
        data:
          topology_desc: "{{ topology_descriptor_content | to_json}}"
          topology_validity: "{{ TOPOLOGY_VALIDITY | bool}}"
          oak_repo_commit: "{{ commit }}"
