name: Trigger AWX Job Template

on:  
  workflow_dispatch:
    inputs:
      topology:
        description: 'Testbed repository - topology descriptor'
        required: true
        default: 'topology.json'
      branch:
        description: 'Oakestra repo branch'
        required: true
        default: 'main'
      commit:
          description: 'Oakestra repo commit'
          required: true
          type: string
          default: 'HEAD'

jobs:
  trigger-awx-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read topology file ${{ github.event.inputs.topology }}
        id: read_topology
        run: |
          cat ${{ github.event.inputs.topology }} 

      - name: Trigger Testbed Pipeline Execution
        env:
          TOWER_HOST: ${{ secrets.TOWER_HOST }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          TOWER_API_TOKEN: ${{ secrets.TOWER_TOKEN }}
          BRANCH: ${{ github.event.inputs.branch }}
          COMMIT: ${{ github.event.inputs.commit }}
          FILENAME: ${{ github.event.inputs.topology }}
          
        run: |
          extra_vars_data=$(echo "{\"topology_descriptor\": \"$FILENAME\", \"branch\": \"$BRANCH\", \"commit\": \"$COMMIT\"}")
          echo "$extra_vars_data"
        
          response=$(curl -s -X POST "http://$TOWER_HOST/api/v2/workflow_job_templates/$TEMPLATE_ID/launch/" \
            -H "Authorization: Bearer $TOWER_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{ \"extra_vars\": $extra_vars_data }" \
            --insecure)  # --insecure is equivalent to validate_certs: false in Ansible
          echo "$response" | jq .
